version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}/webui:dev
    build:
      context: .
      dockerfile: src/Web/Dockerfile

  api:
    image: ${DOCKER_REGISTRY-}/api:dev
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile

