name: Docker Deploy to Dev

on:
  push:
    branches:
      - main

    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:
  docker_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo "Docker Test Not Implemented Yet!"
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Docker build of a stack
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose --file docker-compose.yml build
            docker-compose ps
          else
            echo "Docker Build Not Implemented Yet!"
          fi
      
      # install the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login

      - name: Push image to DigitalOcean Container Registry
        run: docker-compose push 

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build

    steps:
      # Login to the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          envs: REGISTRY,GITHUB_SHA          
          script: |
            # Positioning
            sudo docker-compose --version
            sudo ls
            # Snap like a Snack
            # Checking Doctl connect to docker 
            snap connect doctl:dot-docker
            
            # Let see what you have
            sudo docker-compose ps
            
            # Stop running container
            sudo docker-compose down
            
            # Pull Down Staff
            #docker-compose pull

            # Run a new container from a new image 
            #docker-compose up -d 
