name: Docker Deploy to Dev

on:
  push:
    branches:
      - main
    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
       
      - name: Run a multi-line script
        #tar -C /myfolder -xvf file_name.tar
        run: |
          mkdir build
          cp -f docker-compose.* build
          tar -cvf deploy.tar build
          tar -xvf deploy.tar
          
      - name: Distribute new update
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: deploy.tar
          target: "qbx/deployments/"
          
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: |
          doctl registry login
          ls
          ls ~/qbx/deployments/
          docker-compose --file "docker-compose.yml" up --detach
          docker-compose ps       
  
