name: Docker Deploy to Dev

on:
  push:
    branches:
      - 'main'
    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
       
      - name: Run a multi-line script
        #tar -C /myfolder -xvf file_name.tar
        run: |
          mkdir build
          cp -f docker-compose.* .env build
          tar -cvf deploy.tar build
          
          
      - name: Distribute new update
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: deploy.tar
          target: "qbx/deployments/"
      
      - name: Recreate new release
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd qbx/deployments/
            ls
            tar -xvf deploy.tar
            cd build
            ls
            docker-compose pull
            docker-compose up --detach
            docker-compose ps
        
