name: Docker CD to Private Host

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /qbx/deployments/
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USER }}
        remote_key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
            
  

