name: Docker Deploy to Dev

on:
  push:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - dev*

env:
  # TODO: Change variable to your image's name.qbx-container-registry
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"
  IMAGE_NAME: webui-dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file ./WebUI/Dockerfile
          fi

