name: Docker Deploy to Dev

on:
  push:
    branches:
      - main

    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"
  IMAGE_NAME: webui-dev

jobs:
  docker_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo "Docker Test Not Implemented Yet!"
          fi
  build:
    runs-on: ubuntu-latest
    needs: docker_test
    steps:
      - uses: actions/checkout@v2
        
      - name: Docker Buils a Stack
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose --file docker-compose.yml build
          else
            echo "Docker Build Not Implemented Yet!"
          fi
      
      # install the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login

      - name: Push image to DigitalOcean Container Registry
        run: docker-compose push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA
          script: |
            # Stop running container
            docker stop $(echo $IMAGE_NAME)

            # Remove old container
            docker rm $(echo $IMAGE_NAME)
            
            # Checking Doctl connect to docker 
            snap connect doctl:dot-docker
            
            # Run a new container from a new image 
            # docker-compose --file docker-compose.yml run \
            docker imeges
            docker ps
            docker run -d -p 8000:80 --name $(echo $IMAGE_NAME) $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
