name: Docker Deploy to Dev

on:
  push:
    branches:
      - main

    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:
  docker_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo "Docker Test Not Implemented Yet!"
          fi
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Docker build of a stack
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose --file docker-compose.yml build
            docker-compose ps
          else
            echo "Docker Build Not Implemented Yet!"
          fi
      # Login to the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login
      
      - name: Up and Run Apps & Services
        run:  docker-compose --file "docker-compose.yml" up --detach
      
      - name: Push image to DigitalOcean Container Registry
        run: docker-compose push    
            
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build

    steps:
              
      - name: Update Apps & Services via ReCreate approach  
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          scp_source: app/*
          scp_target: ~/qbx-apps-services
          before_script: |
            df -h
          after_script: |
            whoami
          script: |
            # Positioning
            sudo docker-compose --version
            sudo ls la
            # Snap like a Snack
            # Checking Doctl connect to docker 
            snap connect doctl:dot-docker
            
            # Let see what you have
            sudo docker-compose ps
            
            # Stop running container
            sudo docker-compose down
            
            # Pull Down Staff
            docker-compose pull

            # Run a new container from a new image 
            docker-compose up -d     
  
