name: Docker Deploy to Dev

on:
  push:
    branches:
      - 'main'
    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
     
     # Login to the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login
      
      - name: Up and Run Apps & Services
        run: |
          docker-compose --file "docker-compose.yml" up --detach
          docker-compose ps
        
      - name: Push image to DigitalOcean Container Registry
        run: docker-compose push    
     
      - name: Run a multi-line script
        #tar -C /myfolder -xvf file_name.tar
        run: |
          mkdir build
          cp -f docker-compose.* .env build
          tar -cvf 'deploy${{ github.sha}}.tar' build
          
          
      - name: Distribute new update
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'deploy${{ github.sha}}.tar'
          target: "qbx/deployments/"
      
      - name: Recreate new release
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd qbx/deployments/
            ls
            rm -r build
            tar -xvf 'deploy${{ github.sha}}.tar'
            cd build
            ls
            docker-compose pull
            docker-compose down
            docker-compose up --detach
            docker-compose ps
        
