name: Docker Deployment

on:
  push:
    branches:
      - '!main'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker Host
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
          script: |
            mkdir deployment && cd deployment
            ls
            docker-compose pull            
  

