name: Docker Deploy to Dev

on:
  push:
    branches:
      - main
    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # Login to the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login
       
      - name: Run a multi-line script
        #tar -C /myfolder -xvf file_name.tar
        run: |
          mkdir ../build
          cp -TR docker-compose.yml ../build
          tar -cvf echo "deploy${{github.sha}}.tar" ../build/
          tar -xvf echo "deploy${{github.sha}}.tar"
          
      - name: Distribute new update
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: echo "deploy${{github.sha}}.tar"
          target: "qbx/deployments/"
            
  

