name: Docker Deploy to Dev

on:
  push:
    branches:
      - main
    tags:
      - dev*

env:
  REGISTRY: "registry.digitalocean.com/${{secrets.DIGITALOCEAN_CONTAINER_REGISTRY}}"

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo "Docker Test Not Implemented Yet!"
          fi

      - name: Docker build of a stack
        run: |
          if [ -f docker-compose.yml ]; then
            docker-compose --file docker-compose.yml build
            docker-compose ps
          else
            echo "Docker Build Not Implemented Yet!"
          fi
      # Login to the doctl on the runner
      - name: Install doctl     
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login
      
      - name: Up and Run Apps & Services
        run: |
          docker-compose --file "docker-compose.yml" up --detach
          docker-compose ps
        
      - name: Push image to DigitalOcean Container Registry
        run: docker-compose push    
      
      - name: Run a multi-line script
        #tar -C /myfolder -xvf file_name.tar
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf echo "deploy${{github.sha}}.tar" ../build/
          tar -xvf echo "deploy${{github.sha}}.tar"
          
      - name: Distribute new update
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: echo "deploy${{github.sha}}.tar"
          target: "qbx/deployments/"
        
  
